export const instruments = [
  { id: 'nasdaq-future', name: '纳指期货', displayCode: 'NQ', assetType: 'futures', provider: 'sina', providerSymbol: 'hf_NQ', parser: 'sinaFuture' },
  { id: 'sp500-future', name: '标普500期货', displayCode: 'ES', assetType: 'futures', provider: 'sina', providerSymbol: 'hf_ES', parser: 'sinaFuture' },
  { id: 'nikkei-225', name: '日经225', displayCode: 'N225', assetType: 'index-global', provider: 'sina', providerSymbol: 'b_NKY', parser: 'sinaSimpleIndex' },
  { id: 'topix', name: '东证指数', displayCode: 'TOPIX', assetType: 'index-global', marketGroup: '日本', provider: 'sina', providerSymbol: 'b_TOPIX', parser: 'sinaSimpleIndex' },
  { id: 'sse-composite', name: '上证指数', displayCode: '000001.SH', assetType: 'index-cn', provider: 'sina', providerSymbol: 's_sh000001', parser: 'sinaSimpleIndex' },
  { id: 'xuedilong', name: '雪迪龙', displayCode: '002658.SZ', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sz002658', parser: 'sinaCnStock' },
  { id: 'communication-etf-huaxia', name: '通信ETF华夏', displayCode: '515050.SH', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sh515050', parser: 'sinaCnStock' },
  { id: 'hengtong-optic-electric', name: '亨通光电', displayCode: '600487.SH', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sh600487', parser: 'sinaCnStock' },
  { id: 'tongfu-microelectronics', name: '通富微电', displayCode: '002156.SZ', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sz002156', parser: 'sinaCnStock' },
  { id: 'china-korea-semiconductor-etf', name: '中韩半导体ETF华泰柏瑞', displayCode: '513310.SH', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sh513310', parser: 'sinaCnStock' },
  { id: 'changxin-technology', name: '长鑫科技', displayCode: '688825.SH', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sh688825', parser: 'sinaCnStock' },
  { id: 'semiconductor-equipment-etf', name: '半导体设备ETF易方达', displayCode: '159558.SZ', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sz159558', parser: 'sinaCnStock' },
  { id: 'jcet', name: '长电科技', displayCode: '600584.SH', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sh600584', parser: 'sinaCnStock' },
  { id: 'chinext-50', name: '创业板50', displayCode: '399673.SZ', assetType: 'index-cn', provider: 'sina', providerSymbol: 'sz399673', parser: 'sinaCnStock' },
  { id: 'star-50', name: '科创50', displayCode: '000688.SH', assetType: 'index-cn', provider: 'sina', providerSymbol: 'sh000688', parser: 'sinaCnStock' },
  { id: 'unitree-technology', name: '宇树科技-W', displayCode: '688836.SH', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sh688836', parser: 'sinaCnStock' },
  { id: 'eoptolink', name: '中际旭创', displayCode: '300308.SZ', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sz300308', parser: 'sinaCnStock' },
  { id: 'boe-a', name: '京东方A', displayCode: '000725.SZ', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sz000725', parser: 'sinaCnStock' },
  { id: 'satellite-etf-yongying', name: '卫星ETF永赢', displayCode: '159206.SZ', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sz159206', parser: 'sinaCnStock' },
  { id: 'dividend-low-vol-etf', name: '红利低波ETF华泰柏瑞', displayCode: '512890.SH', assetType: 'stock-cn', provider: 'sina', providerSymbol: 'sh512890', parser: 'sinaCnStock' },
  { id: 'japan-topix-etf-csop', name: '日本东证指数ETF南方', displayCode: '513800.SH', assetType: 'stock-cn', marketGroup: '日本', provider: 'sina', providerSymbol: 'sh513800', parser: 'sinaCnStock' },
  { id: 'nikkei-225-etf-efund', name: '日经225ETF易方达', displayCode: '513000.SH', assetType: 'stock-cn', marketGroup: '日本', provider: 'sina', providerSymbol: 'sh513000', parser: 'sinaCnStock' },
  { id: 'nikkei-etf-huaxia', name: '日经ETF华夏', displayCode: '513520.SH', assetType: 'stock-cn', marketGroup: '日本', provider: 'sina', providerSymbol: 'sh513520', parser: 'sinaCnStock' },
  { id: 'nikkei-etf-icbc', name: '日经ETF工银', displayCode: '159866.SZ', assetType: 'stock-cn', marketGroup: '日本', provider: 'sina', providerSymbol: 'sz159866', parser: 'sinaCnStock' },
  { id: 'nikkei-225-etf-huaan', name: '日经225ETF华安', displayCode: '513880.SH', assetType: 'stock-cn', marketGroup: '日本', provider: 'sina', providerSymbol: 'sh513880', parser: 'sinaCnStock' },
  { id: 'nasdaq-100-etf-cmf', name: '纳斯达克100ETF招商', displayCode: '159659.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz159659', parser: 'sinaCnStock' },
  { id: 'nasdaq-100-lof', name: '纳斯达克100LOF', displayCode: '161130.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz161130', parser: 'sinaCnStock' },
  { id: 'nasdaq-etf-guotai', name: '纳指ETF国泰', displayCode: '513100.SH', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sh513100', parser: 'sinaCnStock' },
  { id: 'nasdaq-etf-guangfa', name: '纳指ETF广发', displayCode: '159941.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz159941', parser: 'sinaCnStock' },
  { id: 'nasdaq-etf-harvest', name: '纳指ETF嘉实', displayCode: '159501.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz159501', parser: 'sinaCnStock' },
  { id: 'usa-50-etf-efund', name: '美国50ETF易方达', displayCode: '513850.SH', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sh513850', parser: 'sinaCnStock' },
  { id: 'sp-info-tech-lof', name: '标普信息科技LOF', displayCode: '161128.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz161128', parser: 'sinaCnStock' },
  { id: 'usa-50-etf-chinauniversal', name: '美国50ETF汇添富', displayCode: '159577.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz159577', parser: 'sinaCnStock' },
  { id: 'nasdaq-tech-etf-invesco', name: '纳指科技ETF景顺', displayCode: '159509.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz159509', parser: 'sinaCnStock' },
  { id: 'sp500-etf-guotai', name: '标普500ETF国泰', displayCode: '159612.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz159612', parser: 'sinaCnStock' },
  { id: 'nasdaq-etf-efund', name: '纳指ETF易方达', displayCode: '159696.SZ', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sz159696', parser: 'sinaCnStock' },
  { id: 'sp500-etf-bosera', name: '标普500ETF博时', displayCode: '513500.SH', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sh513500', parser: 'sinaCnStock' },
  { id: 'global-chip-lof', name: '全球芯片LOF', displayCode: '501225.SH', assetType: 'stock-cn', marketGroup: '美国', provider: 'sina', providerSymbol: 'sh501225', parser: 'sinaCnStock' },
  { id: 'samsung', name: '三星电子', displayCode: 'KS005930', assetType: 'stock-kr', marketGroup: '韩国', provider: 'sina', providerSymbol: 'b_KS005930', parser: 'sinaSimpleIndex' },
  { id: 'sk-hynix', name: 'SK海力士', displayCode: 'KS000660', assetType: 'stock-kr', marketGroup: '韩国', provider: 'sina', providerSymbol: 'b_KS000660', parser: 'sinaSimpleIndex' },
  { id: 'hynix-2x-csop', name: '南方两倍做多海力士', displayCode: '07709', assetType: 'stock-kr', marketGroup: '韩国', provider: 'sina', providerSymbol: 'hk07709', parser: 'sinaHkStock' },
  { id: 'kospi', name: '首尔综合指数', displayCode: 'HQ.KOSPI', assetType: 'index-kr', marketGroup: '韩国', provider: 'sina', providerSymbol: 'b_KOSPI', parser: 'sinaSimpleIndex' },
  { id: 'samsung-2x-csop', name: 'XL二南三星', displayCode: '07747', assetType: 'stock-kr', marketGroup: '韩国', provider: 'sina', providerSymbol: 'hk07747', parser: 'sinaHkStock' },
  { id: 'brent-oil', name: '布伦特原油', displayCode: 'OIL', assetType: 'commodity-global', marketGroup: '全球', provider: 'sina', providerSymbol: 'hf_OIL', parser: 'sinaFuture' },
  { id: 'spot-gold', name: '现货黄金', displayCode: 'XAU', assetType: 'commodity-global', marketGroup: '全球', provider: 'sina', providerSymbol: 'hf_XAU', parser: 'sinaFuture' },
  { id: 'bitcoin-usd', name: '比特币美元指数(BTC/USD)', displayCode: 'BTCUSD', assetType: 'crypto-global', marketGroup: '全球', provider: 'sina', providerSymbol: 'fx_sbtcusd', parser: 'sinaForex' }
]
